version: "3.7"

services:
  web:
    image: odoo:17.0
    environment:
      - DB_HOST=dpg-ctv3j9l6l47c739rre60-a.oregon-postgres.render.com
      - DB_PORT=5432
      - DB_USER=younes
      - DB_PASSWORD=AxiNpVes7KhvgrTpPEZoSRNRtT4J8vn7
      - DB_NAME=bst
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: younes
      POSTGRES_PASSWORD: AxiNpVes7KhvgrTpPEZoSRNRtT4J8vn7
      POSTGRES_DB: bst
    ports:
      - "5432:5432"
